### User sign in endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "firstname":"Rubén",
    "lastname":"Serra i Viusà",
    "gender":"male",
    "birthdate":"1974-09-15T03:00:00.000Z",
    "locales":"ca-CA",
    "language":"ca_CA",
    "dni": "43527459G",
    "role":"admin",
    "image":"/images/RubenSerra.jpg",
    "emailhome":"rserravi@gmail.com",
    "emailwork": "rubotic1@gmail.com",
    "streetaddress": "Costa Rica n5",
    "cityaddress": "Las Gabias",
    "stateaddress": "Granada",
    "postalcodeaddress": "18010",
    "countryaddress":"Spain",
    "phonehome": "+34722303012",
    "phonework": "+34722303012",
    "whatsapp":  "+34722303012",
    "socialmedia1":"Facebook",
    "socialmedia2":"Twitter",
    "socialmedia3":"Instagram",
    "socialuser1":"@rserravi",
    "socialuser2":"@rserravi",
    "socialuser3":"@rserravi",
    "password":"password1234",
    "lastlogin": ""
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json
 
{
   "email": "rubotic1@gmail.com",
   "password": "pass"
}

### Get a user profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1Ym90aWMxQGdtYWlsLmNvbSIsImlhdCI6MTY1ODgyNTg5MCwiZXhwIjoxNjU4ODI2NzkwfQ.4A-LWymg37-UfaH8TerytxA1LFMe_XuKP-CIgiq7ZjU

### Get Refresh Token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoicnVib3RpYzFAZ21haWwuY29tIiwiaWF0IjoxNjU4NDAwOTc0LCJleHAiOjE2NjA5OTI5NzR9.kiSj6MUXPzfCpE7XEZ2d64JeFqo46eL69hC4vdJHHLo

### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json
 
{
   "email": "rubotic1@gmail.com"
}

### Update new password endpoint
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json
 
{
   "email": "rubotic1@gmail.com",
   "pin": "776981",
   "newPassword": "password2"
}

### User Logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1Ym90aWMxQGdtYWlsLmNvbSIsImlhdCI6MTY1ODQ3NDUyMiwiZXhwIjoxNjU4NDc1NDIyfQ.-CinF2ScojResh-R3uxshu9Cqc6x0pRGfBiz3CHTecw

### Create customer endpoint
POST http://localhost:3001/v1/customer 
Content-Type: application/json

{
      "promotedToCustomer":"2019-04-02T17:30:00.000Z",
      "firstname": "Juanjo",
      "lastname": "Rubio Burguillos",
      "dni":"43444444G",
      "birthdate": "1974-04-04T17:30:00.000Z",
      "image": "juanjorubio.jpg",
      "gender": "male",
      "inbound": "customer",
      "emailhome":"jrubio@telecom.es",
      "emailwork":"juanr@telefonica.es",
      "streetaddress": "21 E 2nd St",
      "cityaddress": "New York",
      "stateaddress": "NY",
      "postalcodeaddress": "10003",
      "countryaddress":"United States",
      "phonehome":"212 555-1234",
      "phonework":"+34 722303012",   
      "whatsapp": "+34 722303012",
      "socialmedia1":"Facebook",
      "socialmedia2":"Twitter",
      "socialmedia3":"Reddit",
      "socialuser1": "@juanjo.rubio.7798",
      "socialuser2": "@TeresaRodr_",
      "socialuser3": "@TeresaRo12",
      "releaseForm":{
               "file":"",
               "generated":false,
               "signed":false
      }
}

### Get all customers endpoint
GET http://localhost:3001/v1/customer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1Ym90aWMxQGdtYWlsLmNvbSIsImlhdCI6MTY1ODU4OTM0MywiZXhwIjoxNjU4NTkwMjQzfQ.7yfKuTTRCiP7nkZ-unzXEWi830ofYCu8yNrRidTDJlw

### Add language endpoint
POST http://localhost:3001/v1/lang
Content-Type: application/json

{
   "name":"English",
   "language":"en-EN"
}

### Get all languajes endpoint
GET http://localhost:3001/v1/lang
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1Ym90aWMxQGdtYWlsLmNvbSIsImlhdCI6MTY1ODc0NDIzMiwiZXhwIjoxNjU4NzQ1MTMyfQ.1E4l3vrcBlHxRlkT3Y1CSaf6MvDilZL8T_Sj0A712TQ

### Update User
PATCH http://localhost:3001/v1/user/62de6ba9a8b853169103772e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1Ym90aWMxQGdtYWlsLmNvbSIsImlhdCI6MTY1ODgyNTg5MCwiZXhwIjoxNjU4ODI2NzkwfQ.4A-LWymg37-UfaH8TerytxA1LFMe_XuKP-CIgiq7ZjU
Content-Type: application/json

{
    "_id":"62dfd5e43723fc74a96b4db4",
    "firstname":"Rubén",
    "lastname":"Serra i Viusàaaa",
    "gender":"male",
    "birthdate":"1974-09-15T03:00:00.000Z",
    "locales":"ca-CA",
    "dni": "43527459G",
    "role":"admin",
    "image":"/images/RubenSerra.jpg",
    "emailhome":"rserravi@gmail.com",
    "emailwork": "rubotic1@gmail.com",
    "streetaddress": "Costa Rica n5",
    "cityaddress": "Las Gabias",
    "stateaddress": "Granada",
    "postalcodeaddress": "18010",
    "countryaddress":"Spain",
    "phonehome": "+34722303012",
    "phonework": "+34722303012",
    "whatsapp":  "+34722303012",
    "socialmedia1":"Facebook",
    "socialmedia2":"Twitter",
    "socialmedia3":"Instagram",
    "socialuser1":"@rserravi",
    "socialuser2":"@rserravi",
    "socialuser3":"@rserravi",
    "lastlogin": ""
}


### Create a history
POST http://localhost:3001/v1/history
Content-Type: application/json

{
   "userId":"62dfd5e43723fc74a96b4db4",
   "customerId":"62dbd3fe9484f9c059bc5f4d",
   "date":"2022-01-02T17:30:00.000Z",
   "duration":"60",
   "service":"1",
   "cabin":"1",
   "price":"50",
   "paid":"0",
   "status":"pending",
   "closed":"",
   "notes":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
   "attachment":[
      {

      }
   ]
}

### Get history by userid and customerid
GET http://localhost:3001/v1/history
Content-Type: application/json

{
   "userId":"62dfd5e43723fc74a96b4db4",
   "customerId":"62dbd3fe9484f9c059bc5f4d"
}

### Get historuy by _id
GET http://localhost:3001/v1/history
Content-Type: application/json

{
   "_id":"62e0e947cd60c039a0507673"
}

### Update a history
PUT http://localhost:3001/v1/history
Content-Type: application/json

{
   "_id":"62e02ad4442876a7c244b28c",
   "userId":"62dfd5e43723fc74a96b4db4",
   "customerId":"62dbd3fe9484f9c059bc5f4d",
   "date":"2019-04-02T17:30:00.000Z",
   "duration":50,
   "service":"2",
   "cabin":"1",
   "price":50,
   "paid":30,
   "status":"paid",
   "closed":"2019-04-04T17:30:00.000Z",
   "notes":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
   "attachment":[
      {

      }
   ]
}

### Delete a history
DELETE http://localhost:3001/v1/history
Content-Type: application/json

{
   "_id":"62e0205b48d13c09b7a092a5"
}

### Get Debts
GET  http://localhost:3001/v1/history/deposits
Content-Type: application/json

{
   "userId":"62dfd5e43723fc74a96b4db4",
   "fromDate":"2018-07-30"
}

### Create Service
POST http://localhost:3001/v1/services
Content-Type: application/json

{
   "serviceName":"Consulta",
   "priceXHour":30
}

### Get All Services
GET  http://localhost:3001/v1/services
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoicnVib3RpYzFAZ21haWwuY29tIiwiaWF0IjoxNjU4OTA0NTUzLCJleHAiOjE2NjE0OTY1NTN9.sV7wzrN23FDGVD5CoGvyIHfb8HQgQ3BInTIxNScjiaQ

### Create Cabin
POST http://localhost:3001/v1/cabins
Content-Type: application/json

{
   "cabinName":"Visita",
   "description":"Sortida a domicili"
}
